version: '3.9'

services:
  # API Gateway
  api-gateway:
    container_name: Restourand-gateway
    build: .
    ports:
      - "8000:8080"
    networks:
      - GLhost

# Docker Networks
networks:
  GLhost:
      external: true
      name: global-network

# Docker Volumes
volumes:
  db: