version: '3.9'

services:

  migrate:
    image: migrate/migrate
    networks:
      - GLhost
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  
                "postgres://postgres:root@post-restorant:5432/restourand_db?sslmode=disable", 
                "up" ]
    depends_on:
      - postgres-db

  # Postgres Database
  postgres-db:
    container_name: post-restorant
    image: postgres:latest
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: root
      # PGDATA: /data/postgres
      POSTGRES_DB: restourand_db
    volumes:
      - db:/post-database/post-memory
    ports:
      - "5434:5432"
    networks:
      - GLhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  restourand-service:
    container_name: restourand-service
    build: .
    depends_on:
      - postgres-db
    ports:
      - "50020:8082"
    networks:
      - GLhost

# Docker Networks
networks:
  GLhost:
    external: true
    name: global-network
    driver: bridge

# Docker Volumes
volumes:
  db: